package models;

/**
 * Created by Nhan on 3/7/2017.
 */
public enum CharacterState {
    STANDING,
    WALKING_LEFT,
    WALKING_RIGHT,
    WALKING_DOWN,
    WALKING_UP,
    RUNNING_LEFT,
    RUNNING_RIGHT,
    JUMPING,
    ATTACKING_NORMAL,
    SKILL_SHOOTING,
    STUN_NORMAL_1,
    STUN_NORMAL_2,
    FALL_LEFT,
    FALL_RIGHT,
    DEAD,
    ELEVATING,
    ELEVATING_WALKING_RIGHT,
    ELEVATING_WALKING_LEFT,
    ELEVATING_WALKING_DOWN,
    ELEVATING_WALKING_UP,
    ELEVATING_RUNNING_LEFT,
    ELEVATING_RUNNING_RIGHT,
    THROWING
}
